# Default values for cronjobs.
schedulers:
- name: scheduler1
  schedule:  "*/1 * * * *"
  script: |
    echo "Hello World, from scheduler1!"
- name: scheduler2
  schedule:  "*/2 * * * *"
  script: |
    echo "Hello World, from scheduler2!"

image:
  repository: busybox
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

# environment variables stores as secrets
env: {}

podAnnotations: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

