apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cronjobs.fullname" . }}
  labels:
    {{- include "cronjobs.labels" . | nindent 4 }}
data:
  {{- range .Values.schedulers }}
  {{ .name }}.sh: |-
{{ .script | indent 4 }}
  {{- end }}
