apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cronjobs.fullname" . }}
  labels:
    {{- include "cronjobs.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.env }}
  {{ $key | lower }}: {{ $val | b64enc }}
  {{- end}}
